using Ploeh.AutoFixture.Xunit2;

namespace Kleu.Utility.Testing
{
    /// <inheritdoc />
    /// <summary>
    /// When placed on a test method, this attribute will cause method parameters to be automatically generated by AutoFixture as configured in <see cref="!:DefaultFixture" />.
    /// </summary>
    public class DefaultFixtureAttribute : AutoDataAttribute
    {
        public DefaultFixtureAttribute() : base(new DefaultFixture())
        {

        }
    }
}
